server:
  port: 8070
spring:
  application:
    name: dubbo-user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
sidecar:
  port: 8080                                 # Dubbo微服务的端口
  health-uri: http://localhost:8080/health   # Dubbo微服务的健康检查URL